# Advanced data types

## Vector: 1 dimension, all data has to be the same type

In [4]:
vector1 = c(1:20)
vector1
length(vector1)
mode(vector1)
class(vector1)
typeof(vector1)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[1] 20

[1] "numeric"

[1] "integer"

[1] "integer"

## Matrix: 2 dimensions or more, all data has to be the same type

In [5]:
matrix1 = matrix(1:20, nrow = 5)
matrix1
length(matrix1)
mode(matrix1)
class(matrix1)
typeof(matrix1)

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

[1] 20

[1] "numeric"

[1] "matrix"

[1] "integer"

## Array: 2 dimensions or more, all data has to be the same type

In [7]:
array1 = array(1:5, dim = c(3,3,3))
array1
length(array1)
mode(array1)
class(array1)
typeof(array1)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    2
[2,]    2    5    3
[3,]    3    1    4

, , 2

     [,1] [,2] [,3]
[1,]    5    3    1
[2,]    1    4    2
[3,]    2    5    3

, , 3

     [,1] [,2] [,3]
[1,]    4    2    5
[2,]    5    3    1
[3,]    1    4    2

[1] 27

[1] "numeric"

[1] "array"

[1] "integer"

## Dataframe: A matrix with different types of data

In [11]:
head(iris)
mode(iris)
class(iris)
typeof(iris)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

[1] "list"

[1] "data.frame"

[1] "list"

## List: A collection that supports different types of data

In [14]:
list1 <- list(a = matrix1, b = vector1)
list1
length(list1)
mode(list1)
class(list1)
typeof(list1)

$a
     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20

$b
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[1] 2

[1] "list"

[1] "list"

[1] "list"

## Functions: Are objects

In [15]:
func1 = function(x) {
    var1 <- x * x
    return(var1)
}

In [16]:
func1(5)

[1] 25

In [17]:
class(func1)

[1] "function"

In [18]:
objects()

[1] "array1"  "func1"   "list1"   "matrix1" "vector1"