# Matrix

In [2]:
A = matrix(c(1:6), nrow = 2)
A

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [4]:
B = matrix(c(1:6), nrow = 3)
B

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [5]:
C = matrix(c(1:6), nrow = 6)
C

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6

In [6]:
D = matrix(c(1:6), nc = 2)
D

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [7]:
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘matrix’ creates a matrix from the given set of values.

     ‘as.matrix’ attempts to turn its argument into a matrix.

     ‘is.matrix’ tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or ‘expression’
          vector).  Non-atomic classed R objects are coerced by
          ‘as.vector’ and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If ‘FALSE’ (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A ‘dimnames’ attribute for the matrix: ‘NULL’ or a ‘list’ of
          length 2 giving the row and column names respectively.  An
          empty list is treated as ‘NULL’, and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than ‘NULL’) ‘rownames’.  The default,
          ‘NA’, uses ‘NULL’ rownames if the data frame has ‘automatic’
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of ‘nrow’ or ‘ncol’ is not given, an attempt is made to
     infer it from the length of ‘data’ and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in ‘data’ to fill the matrix, then
     the elements in ‘data’ are recycled.  If ‘data’ has length zero,
     ‘NA’ of an appropriate type is used for atomic vectors (‘0’ for
     raw vectors) and ‘NULL’ for lists.

     ‘is.matrix’ returns ‘TRUE’ if ‘x’ is a vector and has a ‘"dim"’
     attribute of length 2 and ‘FALSE’ otherwise.  Note that a
     ‘data.frame’ is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     ‘as.matrix’ is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying ‘as.vector’ to
     factors and ‘format’ to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for ‘as.matrix’ calls ‘as.vector(x)’, and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     ‘is.matrix’ is a primitive function.

     The ‘print’ method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form ‘integer,7’ indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like
     
       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)

     will avoid duplicating ‘x’.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘data.matrix’, which attempts to convert to a numeric matrix.

     A matrix is the special case of a two-dimensional ‘array’.

_E_x_a

In [9]:
V = c(1:10)
E = matrix(data = V, nrow = 5, ncol = 2, byrow = T)
E

[,1] [,2]
[1,] 1     2  
[2,] 3     4  
[3,] 5     6  
[4,] 7     8  
[5,] 9    10

In [10]:
F = matrix(data = V, nrow = 5, ncol = 2)
F

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

# Slicing

In [12]:
F[1,2]

[1] 6

In [13]:
F[,2]

[1]  6  7  8  9 10

In [14]:
F[1,]

[1] 1 6

In [23]:
G = c(1:3)
diag(G)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [24]:
G

[1] 1 2 3

In [25]:
W <- matrix(c(2,4,6,8), nr = 2, ncol = 2)
W

[,1] [,2]
[1,] 2    6   
[2,] 4    8

In [26]:
t(W)

[,1] [,2]
[1,] 2    4   
[2,] 6    8

In [28]:
#Matrix Inverse
solve(W)

[,1] [,2] 
[1,] -1.0  0.75
[2,]  0.5 -0.25

In [35]:
B
D

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [36]:
B * D

[,1] [,2]
[1,] 1    16  
[2,] 4    25  
[3,] 9    36

In [37]:
B / D

[,1] [,2]
[1,] 1    1   
[2,] 1    1   
[3,] 1    1

In [38]:
B + D

[,1] [,2]
[1,] 2     8  
[2,] 4    10  
[3,] 6    12

In [39]:
B - D

[,1] [,2]
[1,] 0    0   
[2,] 0    0   
[3,] 0    0

In [51]:
mat1 = matrix(c('Terra', 'Marte', 'Saturno', 'Netuno'), nr = 2, nc = 2, dimnames = list(c('line1, line2'), c('col1', 'col2')))
mat1

ERROR: Error in matrix(c("Terra", "Marte", "Saturno", "Netuno"), nr = 2, nc = 2, : length of 'dimnames' [1] not equal to array extent


[[1]]
[1] "line1, line2"

[[2]]
[1] "col1" "col2"

In [48]:
dimnames(mat1) = names

ERROR: Error in dimnames(mat1) = names: length of 'dimnames' [1] not equal to array extent
