# Unlist, do.call and strsplit

In [2]:
lst <- list(6, 'b', 15)
lst
class(lst)

[[1]]
[1] 6

[[2]]
[1] "b"

[[3]]
[1] 15

[1] "list"

In [5]:
vec <- unlist(lst)
vec
class(vec)

[1] "6"  "b"  "15"

[1] "character"

In [6]:
lst2 <- list(v1 = 6, v2 = list(381, 2190), v3 = c(30, 178))
lst2

$v1
[1] 6

$v2
$v2[[1]]
[1] 381

$v2[[2]]
[1] 2190


$v3
[1]  30 178

In [8]:
vec2 <- unlist(lst2)
vec2

v1  v21  v22  v31  v32 
   6  381 2190   30  178

In [9]:
mean(unlist(lst2))

[1] 557

In [11]:
#?do.call
data <- list()
n <- 100

for (i in 1:n) {
    data[[i]] <- data.frame(index = n, char = sample(letters, 1), z = rnorm(1))
}

head(data)

[[1]]
  index char          z
1   100    c -0.9454282

[[2]]
  index char         z
1   100    z 0.5177985

[[3]]
  index char         z
1   100    s -0.626134

[[4]]
  index char         z
1   100    j -1.000394

[[5]]
  index char        z
1   100    f 0.262917

[[6]]
  index char         z
1   100    g -1.041414

In [13]:
df = do.call(rbind, data)
head(df)

index char z         
1 100   c    -0.9454282
2 100   z     0.5177985
3 100   s    -0.6261340
4 100   j    -1.0003939
5 100   f     0.2629170
6 100   g    -1.0414138

In [14]:
y <- list(1:3, 4:6, 7:9)
y

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5 6

[[3]]
[1] 7 8 9

In [15]:
lapply(y, sum)

[[1]]
[1] 6

[[2]]
[1] 15

[[3]]
[1] 24

In [16]:
do.call(sum, y)

[1] 45

In [17]:
install.packages('plyr')
library(plyr)

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [18]:
y <- list(1:3, 4:6, 7:9)
y

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5 6

[[3]]
[1] 7 8 9

In [19]:
# best performance than lapply
ldply(y, sum)

V1
1  6
2 15
3 24

In [20]:
text <- 'World of Data Science'
text

[1] "World of Data Science"

In [23]:
strsplit(text, ' ')

[[1]]
[1] "World"   "of"      "Data"    "Science"

In [24]:
dates <- c('1998-09-12', '2008-05-08')
temp <- strsplit(dates, '-')
temp

[[1]]
[1] "1998" "09"   "12"  

[[2]]
[1] "2008" "05"   "08"

In [25]:
matrix(unlist(temp), ncol = 3, byrow = T)

[,1] [,2] [,3]
[1,] 1998 09   12  
[2,] 2008 05   08

In [29]:
names <- c('Brin', 'Sergey', 'Page', 'Larry', 'Dorsey', 'Jack', 'Glass', 'Noah', 'Williams', 'Evan', 'Stone', 'Biz')
temp <- strsplit(names, ', ')
class(temp)
temp

[1] "list"

[[1]]
[1] "Brin"

[[2]]
[1] "Sergey"

[[3]]
[1] "Page"

[[4]]
[1] "Larry"

[[5]]
[1] "Dorsey"

[[6]]
[1] "Jack"

[[7]]
[1] "Glass"

[[8]]
[1] "Noah"

[[9]]
[1] "Williams"

[[10]]
[1] "Evan"

[[11]]
[1] "Stone"

[[12]]
[1] "Biz"

In [30]:
# unique
frase <- 'Muitas vezes temos que repetir algo diversas vezes e essas diversas vezes parecem algo estranho'
words <- strsplit(frase, ' ')[[1]]
words
unique(tolower(words))

[1] "Muitas"   "vezes"    "temos"    "que"      "repetir"  "algo"    
 [7] "diversas" "vezes"    "e"        "essas"    "diversas" "vezes"   
[13] "parecem"  "algo"     "estranho"

[1] "muitas"   "vezes"    "temos"    "que"      "repetir"  "algo"    
 [7] "diversas" "e"        "essas"    "parecem"  "estranho"

In [31]:
before <- data.frame(attr = c(1,30,4,8), type = c('bread_and_water', 'bread_and_water2'))
before
strsplit(as.character(before$type), '_and_')

attr type            
1  1   bread_and_water 
2 30   bread_and_water2
3  4   bread_and_water 
4  8   bread_and_water2

[[1]]
[1] "bread" "water"

[[2]]
[1] "bread"  "water2"

[[3]]
[1] "bread" "water"

[[4]]
[1] "bread"  "water2"

In [33]:
install.packages('stringr')
library(stringr)

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [34]:
str_split_fixed(before$type, '_and_', 2)

[,1]  [,2]  
[1,] bread water 
[2,] bread water2
[3,] bread water 
[4,] bread water2

In [38]:
before

attr type            
1  1   bread_and_water 
2 30   bread_and_water2
3  4   bread_and_water 
4  8   bread_and_water2

In [41]:
after <- strsplit(as.character(before$type), '_and_')
do.call(rbind, after)

[,1]  [,2]  
[1,] bread water 
[2,] bread water2
[3,] bread water 
[4,] bread water2