# Exercices

In [2]:
# Exercício 1 - Pesquise pela função que permite listar todos os arquivo no diretório de trabalho
list.files(".")

[1] "000-bigdata-byexample.ipynb"  "001-factor.ipynb"            
 [3] "002-controlstructures.ipynb"  "003-functions.ipynb"         
 [5] "004-applyfamily.ipynb"        "005-unlistdocall.ipynb"      
 [7] "006-regex.ipynb"              "007-dates.ipynb"             
 [9] "008-assignmentoperator.ipynb" "009-exercices.ipynb"

In [4]:
# Exercício 2 - Crie um dataframe a partir de 3 vetores: um de caracteres, um lógico e um de números
vec_char = c('a', 'b', 'c', 'd')
vec_log = c(T, F, T, T)
vec_num = c(1:4)
df = data.frame(vec_char, vec_log, vec_num)
df

vec_char vec_log vec_num
1 a         TRUE   1      
2 b        FALSE   2      
3 c         TRUE   3      
4 d         TRUE   4

In [20]:
# Exercício 3 - Considere o vetor abaixo. 
# Crie um loop que verifique se há números maiores que 10 e imprima o número e uma mensagem no console.
# Criando um Vetor
vec1 <- c(12, 3, 4, 19, 34)

for(i in vec1) {
    if (i > 10) {
        print(i)
        print("This number is greater than 10")
    }
}

[1] 12
[1] "This number is greater than 10"
[1] 19
[1] "This number is greater than 10"
[1] 34
[1] "This number is greater than 10"


In [27]:
# Exercício 4 - Conisdere a lista abaixo. Crie um loop que imprima no console cada elemento da lista
lst2 <- list(2, 3, 5, 7, 11, 13)
for (i in lst2) 
    print(i)

[1] 2
[1] 3
[1] 5
[1] 7
[1] 11
[1] 13


In [30]:
# Exercício 5 - Considere as duas matrizes abaixo. 
# Faça uma multiplicação element-wise e multiplicação normal entre as materizes
mat1 <- matrix(c(1:50), nrow = 5, ncol = 5, byrow = T)
mat2 <- t(mat1)
mat1
mat2

# Multiplicação element-wise
mat1 * mat2

# Multiplicação de matrizes
mat1 %*% mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

[,1] [,2] [,3] [,4] [,5]
[1,]   1   12   33   64  105 
[2,]  12   49   96  153  220 
[3,]  33   96  169  252  345 
[4,]  64  153  252  361  480 
[5,] 105  220  345  480  625

[,1] [,2] [,3] [,4] [,5]
[1,]  55  130   205  280  355
[2,] 130  330   530  730  930
[3,] 205  530   855 1180 1505
[4,] 280  730  1180 1630 2080
[5,] 355  930  1505 2080 2655

In [57]:
# Exercício 6 - Crie um vetor, matriz, lista e dataframe e faça a nomeação de cada um dos objetos
vec1 = c(1:4)
names(vec1) = c("vec1")
vec1

A = matrix(3, 3, ncol = 3)
colnames(A) = c('col1', 'col2', 'col3')
rownames(A) = c('row1', 'row2', 'row3')
A

lst1 = list(vector = vec1, matrix = A)
lst1

vec1 <NA> <NA> <NA> 
   1    2    3    4

col1 col2 col3
row1 3    3    3   
row2 3    3    3   
row3 3    3    3

$vector
vec1 <NA> <NA> <NA> 
   1    2    3    4 

$matrix
     col1 col2 col3
row1    3    3    3
row2    3    3    3
row3    3    3    3

In [91]:
# Exercício 7 - Considere a matriz abaixo. Atribua valores NA de forma aletória para 50 elementos da matriz
# Dica: use a função sample()
mat2 <- matrix(1:90, 10)
mat2
mat2[sample(1:50, 10)] = NA
mat2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]  1   11   21   31   41   51   61   71   81  
 [2,]  2   12   22   32   42   52   62   72   82  
 [3,]  3   13   23   33   43   53   63   73   83  
 [4,]  4   14   24   34   44   54   64   74   84  
 [5,]  5   15   25   35   45   55   65   75   85  
 [6,]  6   16   26   36   46   56   66   76   86  
 [7,]  7   17   27   37   47   57   67   77   87  
 [8,]  8   18   28   38   48   58   68   78   88  
 [9,]  9   19   29   39   49   59   69   79   89  
[10,] 10   20   30   40   50   60   70   80   90

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]  1   11   NA   31   41   51   61   71   81  
 [2,] NA   12   22   NA   NA   52   62   72   82  
 [3,] NA   13   NA   33   43   53   63   73   83  
 [4,]  4   14   NA   34   44   54   64   74   84  
 [5,]  5   15   25   35   45   55   65   75   85  
 [6,]  6   NA   26   36   46   56   66   76   86  
 [7,]  7   17   27   37   47   57   67   77   87  
 [8,]  8   18   28   38   48   58   68   78   88  
 [9,]  9   19   29   NA   49   59   69   79   89  
[10,] 10   NA   30   40   50   60   70   80   90

In [92]:
# Exercício 8 - Para a matriz abaixo, calcule a soma por linha e por coluna
mat1 <- matrix(c(1:50), nrow = 5, ncol = 5, byrow = T)
mat1
apply(mat1, 1, sum)
apply(mat1, 2, sum)

rowSums(mat1)
colSums(mat1)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[1]  15  40  65  90 115

[1] 55 60 65 70 75

[1]  15  40  65  90 115

[1] 55 60 65 70 75

In [78]:
# Exercício 9 - Para o vetor abaixo, ordene os valores em ordem crescente
a <- c(100, 10, 10000, 1000)
a
a[order(a)]


[1]   100    10 10000  1000

[1]    10   100  1000 10000

In [90]:
# # Exercício 10 - Imprima no console todos os elementos da matriz abaixo que forem maiores que 15
mat1 <- matrix(c(1:50), nrow = 5, ncol = 5, byrow = T)
great = function(x) { 
    if(x > 15) {
        print(x)
    }
}
for (i in mat1) {
    great(i)
}


[1] 16
[1] 21
[1] 17
[1] 22
[1] 18
[1] 23
[1] 19
[1] 24
[1] 20
[1] 25
